### ISSUE TITLE
Css

### ISSUE THREAD

**Issue by Alexey-T** [dubharmonic/Sublime-W3CValidators#6]
I cannot see menuitem for css, while u have code for it and url for it, why, pls add

**Comment by Ipoumb1988** [comment]
Can you give me order information on this project

**Comment by Alexey-T** [comment]
hehe, irony? yes it\'s free app. (css not done, i see)

**Comment by dubharmonic** [comment]
The CSS validation service currently only works with SOAP, unlike the others. I'd appreciate some help!
